import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, Index, Unique } from "typeorm";

/**
 * trade_labels — triple-barrier supervised labels, the training-data foundation
 * for the meta-label / cross-sectional models. One row per (ticker, anchor,
 * horizon, label version). `feature_hash` links to a feature snapshot once the
 * feature pipeline exists; null until then (labels accrue first, by design).
 * Generated by the SAME barrier discipline that grades live trades.
 */
@Entity("trade_labels")
@Index(["ticker", "anchorDate"])
@Unique("uq_trade_label_identity", ["ticker", "anchorDate", "horizonSessions", "labelVersion"])
export class TradeLabel {
  @PrimaryGeneratedColumn("uuid") id: string;
  @Column({ type: "varchar", length: 20 }) ticker: string;
  @Column({ name: "anchor_date", type: "date" }) anchorDate: string;
  @Column({ name: "horizon_sessions", type: "int" }) horizonSessions: number;

  @Column({ name: "entry_price", type: "numeric", precision: 14, scale: 4 }) entryPrice: string;
  @Column({ type: "numeric", precision: 14, scale: 4 }) atr: string;
  @Column({ name: "upper_mult", type: "numeric", precision: 6, scale: 2 }) upperMult: string;
  @Column({ name: "lower_mult", type: "numeric", precision: 6, scale: 2 }) lowerMult: string;
  @Column({ name: "upper_barrier", type: "numeric", precision: 14, scale: 4 }) upperBarrier: string;
  @Column({ name: "lower_barrier", type: "numeric", precision: 14, scale: 4 }) lowerBarrier: string;

  @Column({ type: "varchar", length: 15 }) label: string; // TARGET | STOP | TIME | AMBIGUOUS | DATA_INVALID
  @Column({ name: "realized_r", type: "numeric", precision: 12, scale: 4, nullable: true }) realizedR: string | null;
  @Column({ name: "conservative_r", type: "numeric", precision: 12, scale: 4, nullable: true }) conservativeR: string | null;
  @Column({ name: "mfe_r", type: "numeric", precision: 12, scale: 4, nullable: true }) mfeR: string | null;
  @Column({ name: "mae_r", type: "numeric", precision: 12, scale: 4, nullable: true }) maeR: string | null;
  @Column({ name: "holding_days", type: "int", default: 0 }) holdingDays: number;
  @Column({ type: "boolean", default: false }) ambiguous: boolean;

  /** Links to a point-in-time feature snapshot once the feature layer exists. */
  @Column({ name: "feature_hash", type: "varchar", length: 64, nullable: true }) featureHash: string | null;
  @Column({ name: "label_version", type: "varchar", length: 40 }) labelVersion: string;
  @CreateDateColumn({ name: "created_at", type: "timestamptz" }) createdAt: Date;
}
