import { MigrationInterface, QueryRunner } from "typeorm";

export class BaselineSchema1788659901107 implements MigrationInterface {
    name = 'BaselineSchema1788659901107'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "financial_facts" DROP CONSTRAINT "FK_financial_fact_source"`);
        await queryRunner.query(`ALTER TABLE "intelligence_evidence" DROP CONSTRAINT "FK_intelligence_evidence_source"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_intelligence_sources_ticker_provider_date"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_financial_facts_lookup"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_intelligence_metrics_lookup"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_intelligence_evidence_lookup"`);
        await queryRunner.query(`ALTER TABLE "financial_facts" DROP CONSTRAINT "UQ_financial_fact_source_concept_context"`);
        await queryRunner.query(`ALTER TABLE "macro_observations" DROP CONSTRAINT "UQ_macro_observation"`);
        await queryRunner.query(`CREATE TYPE "public"."analysis_recommendation_enum" AS ENUM('BUY', 'HOLD', 'SELL', 'AVOID')`);
        await queryRunner.query(`CREATE TYPE "public"."analysis_risk_level_enum" AS ENUM('Low', 'Medium', 'High')`);
        await queryRunner.query(`CREATE TABLE "analysis" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "stock_id" uuid NOT NULL, "summary" text NOT NULL, "recommendation" "public"."analysis_recommendation_enum" NOT NULL, "risk_level" "public"."analysis_risk_level_enum" NOT NULL, "current_price" numeric(10,2), "pe_ratio" numeric(10,2), "rsi" numeric(10,2), "score" numeric(6,2), "price_change_percent" numeric(10,2), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_300795d51c57ef52911ed65851f" PRIMARY KEY ("id")); COMMENT ON COLUMN "analysis"."recommendation" IS 'Investment recommendation based on technical analysis'; COMMENT ON COLUMN "analysis"."risk_level" IS 'Risk assessment based on volatility and market conditions'`);
        await queryRunner.query(`CREATE TABLE "stock_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "stock_id" uuid NOT NULL, "open_price" numeric(12,4) NOT NULL, "high_price" numeric(12,4) NOT NULL, "low_price" numeric(12,4) NOT NULL, "close_price" numeric(12,4) NOT NULL, "previous_close" numeric(12,4), "volume" bigint NOT NULL, "volume_change_percent" numeric(8,4), "price_change" numeric(12,4), "price_change_percent" numeric(8,4), "market_cap" bigint, "pe_ratio" numeric(10,4), "data_source" character varying(50) NOT NULL DEFAULT 'alpha_vantage', "fetch_timestamp" TIMESTAMP NOT NULL DEFAULT now(), "trading_date" date NOT NULL, CONSTRAINT "UQ_79f9fd3f81b5fc9bf629f41a521" UNIQUE ("stock_id", "trading_date", "fetch_timestamp"), CONSTRAINT "PK_16924caa54ac1fa49162ea3afca" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cc252ec5ff13eb9dd089a464d2" ON "stock_history" ("fetch_timestamp") `);
        await queryRunner.query(`CREATE INDEX "IDX_f4735409aecba218d2a47a7594" ON "stock_history" ("trading_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_4c6083eda45a5e0e12e706424f" ON "stock_history" ("stock_id", "trading_date") `);
        await queryRunner.query(`CREATE TABLE "stock_metrics" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "stock_id" uuid NOT NULL, "sma_20" numeric(12,4), "sma_50" numeric(12,4), "sma_200" numeric(12,4), "ema_12" numeric(12,4), "ema_26" numeric(12,4), "rsi_14" numeric(8,4), "macd" numeric(12,4), "macd_signal" numeric(12,4), "macd_histogram" numeric(12,4), "volatility_30d" numeric(8,4), "bollinger_upper" numeric(12,4), "bollinger_middle" numeric(12,4), "bollinger_lower" numeric(12,4), "volume_sma_20" bigint, "volume_momentum" numeric(8,4), "price_volume_ratio" numeric(12,4), "daily_return" numeric(8,4), "cumulative_return" numeric(10,4), "sharpe_ratio" numeric(8,4), "trend_direction" character varying(20), "trend_strength" numeric(5,2), "calculation_timestamp" TIMESTAMP NOT NULL DEFAULT now(), "data_quality_score" numeric(5,2), CONSTRAINT "PK_b0a176b2adaebb01eb253dde8cd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4458bfad30b2757b22cd9376ec" ON "stock_metrics" ("trend_direction") `);
        await queryRunner.query(`CREATE INDEX "IDX_1e2797169280396ab49bb91f4b" ON "stock_metrics" ("rsi_14") `);
        await queryRunner.query(`CREATE INDEX "IDX_6e589ac2bbe419ca83f43cce8a" ON "stock_metrics" ("stock_id", "calculation_timestamp") `);
        await queryRunner.query(`CREATE TABLE "stocks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "ticker" character varying(20) NOT NULL, "exchange" character varying(50), "sector" character varying(100), "industry" character varying(100), "is_active" boolean NOT NULL DEFAULT true, "tracking_enabled" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_67e5527b870ca7e013858ed3d78" UNIQUE ("ticker"), CONSTRAINT "PK_b5b1ee4ac914767229337974575" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_90ea57d41bf1ba91c6981e4ade" ON "stocks" ("is_active", "tracking_enabled") `);
        await queryRunner.query(`CREATE INDEX "IDX_67e5527b870ca7e013858ed3d7" ON "stocks" ("ticker") `);
        await queryRunner.query(`CREATE TABLE "rate_limit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "api_provider" character varying(50) NOT NULL DEFAULT 'alpha_vantage', "endpoint" character varying(100), "ticker" character varying(20), "request_timestamp" TIMESTAMP NOT NULL DEFAULT now(), "response_status" integer, "response_time_ms" integer, "requests_this_minute" integer, "requests_today" integer, "quota_remaining_minute" integer, "quota_remaining_day" integer, "is_error" boolean NOT NULL DEFAULT false, "error_message" text, "retry_count" integer NOT NULL DEFAULT '0', "request_id" character varying(100), "user_agent" character varying(255), CONSTRAINT "PK_0a7dd4e864742b33a3ee2da5bfd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0ec5d60fe5e30c1484ae6a98aa" ON "rate_limit_logs" ("ticker") `);
        await queryRunner.query(`CREATE INDEX "IDX_a47b99659613a5464a6bcd2d3d" ON "rate_limit_logs" ("api_provider", "request_timestamp") `);
        await queryRunner.query(`CREATE INDEX "IDX_ed3365b823c13b0828fa5f29ca" ON "rate_limit_logs" ("request_timestamp") `);
        await queryRunner.query(`CREATE TABLE "cron_execution_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "job_name" character varying(100) NOT NULL, "execution_start" TIMESTAMP NOT NULL, "execution_end" TIMESTAMP, "execution_duration_ms" integer, "status" character varying(20), "stocks_processed" integer NOT NULL DEFAULT '0', "stocks_failed" integer NOT NULL DEFAULT '0', "api_calls_made" integer NOT NULL DEFAULT '0', "error_summary" text, "success_rate" numeric(5,2), "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7143e1900be6461037b4a8ce56a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_312d2d22eb16ebdcf477c6504c" ON "cron_execution_logs" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_dd9b32c339b5ba46c1a84c3aa0" ON "cron_execution_logs" ("job_name", "execution_start") `);
        await queryRunner.query(`CREATE TABLE "training_samples" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "ticker" character varying(20) NOT NULL, "date" date NOT NULL, "features" jsonb NOT NULL, "target_return" numeric(10,4) NOT NULL, "target_direction" smallint NOT NULL, "target_volatility" numeric(10,4) NOT NULL, "feature_quality" numeric(5,2) NOT NULL, "market_regime" character varying(20) NOT NULL, "sector" character varying(50), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "train_set" boolean NOT NULL DEFAULT false, "validation_set" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_dd4fee6a280825b981ae2246399" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d0de7d8eefb2a0711ca74a4665" ON "training_samples" ("date") `);
        await queryRunner.query(`CREATE INDEX "IDX_1bcaeebd54521d9e08b069e0e8" ON "training_samples" ("target_direction") `);
        await queryRunner.query(`CREATE INDEX "IDX_263fd13ae5081852e6ca4a817e" ON "training_samples" ("ticker", "date") `);
        await queryRunner.query(`CREATE TABLE "model_registry" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "model_name" character varying(100) NOT NULL, "version" character varying(50) NOT NULL, "model_type" character varying(50) NOT NULL, "artifacts_path" text NOT NULL, "performance" jsonb NOT NULL, "training_samples" integer NOT NULL, "test_samples" integer NOT NULL, "training_date_range" jsonb NOT NULL, "feature_count" integer NOT NULL, "hyperparameters" jsonb NOT NULL, "feature_importance" jsonb, "is_production" boolean NOT NULL DEFAULT false, "deployment_date" TIMESTAMP WITH TIME ZONE, "deprecated_date" TIMESTAMP WITH TIME ZONE, "parent_model_id" uuid, "notes" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ab5547e9cddf7f8abf6c462bd64" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f55830c6120cba8b1a55c69121" ON "model_registry" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_2a30d1386addd706a59abfaff1" ON "model_registry" ("is_production") `);
        await queryRunner.query(`CREATE INDEX "IDX_a29d3b86c5655964fc148df010" ON "model_registry" ("model_name", "version") `);
        await queryRunner.query(`CREATE TABLE "prediction_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "ticker" character varying(20) NOT NULL, "prediction_date" date NOT NULL, "model_version" character varying(50) NOT NULL, "predicted_direction" character varying(20) NOT NULL, "predicted_probability" numeric(5,4) NOT NULL, "confidence" numeric(5,4) NOT NULL, "expected_return" numeric(10,4) NOT NULL, "expected_volatility" numeric(10,4), "horizon_days" integer, "target_date" date, "base_price" numeric(12,4), "expected_price" numeric(12,4), "low80_pct" numeric(10,4), "high80_pct" numeric(10,4), "score" numeric(6,2), "models_agreement" numeric(5,2), "prediction_uncertainty" character varying(20), "model_predictions" jsonb, "feature_vector" jsonb, "feature_quality" numeric(5,2), "actual_return" numeric(10,4), "actual_direction" character varying(20), "prediction_correct" boolean, "outcome_date" date, "recommendation_given" character varying(50), "fundamental_score" numeric(5,2), "risk_warnings" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9413cebaa48a6674bd0836eebb7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_956e0bab09fd4308d65b5d11e8" ON "prediction_logs" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_e7899294dc3846d07ecf04a45e" ON "prediction_logs" ("prediction_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_7cca4cae8ab0866704bd243180" ON "prediction_logs" ("model_version") `);
        await queryRunner.query(`CREATE INDEX "IDX_8afbc587e50337b08dcd8d6ef9" ON "prediction_logs" ("ticker", "prediction_date") `);
        await queryRunner.query(`CREATE TABLE "model_performance" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "model_version" character varying(50) NOT NULL, "ticker" character varying(20), "test_days" integer, "ran_at" TIMESTAMP WITH TIME ZONE, "horizons" jsonb, "period_start" date NOT NULL, "period_end" date NOT NULL, "aggregation_level" character varying(20) NOT NULL, "total_predictions" integer NOT NULL, "correct_predictions" integer NOT NULL, "accuracy" numeric(5,4) NOT NULL, "precision" numeric(5,4), "recall" numeric(5,4), "f1_score" numeric(5,4), "average_return" numeric(10,4), "sharpe_ratio" numeric(10,4), "sortino_ratio" numeric(10,4), "max_drawdown" numeric(10,4), "win_rate" numeric(5,4), "avg_confidence" numeric(5,4), "high_confidence_accuracy" numeric(5,4), "low_confidence_accuracy" numeric(5,4), "feature_drift_score" numeric(5,4), "prediction_drift_score" numeric(5,4), "accuracy_below_threshold" boolean NOT NULL DEFAULT false, "significant_drift_detected" boolean NOT NULL DEFAULT false, "retraining_recommended" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_00362e2756eeda9994b347384f8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_5ce1a82d1bdcd1a3327079f5b2" ON "model_performance" ("ticker", "model_version") `);
        await queryRunner.query(`CREATE INDEX "IDX_6cac3a44e37dfe68bdea52faa6" ON "model_performance" ("ticker") `);
        await queryRunner.query(`CREATE INDEX "IDX_caa57b9555c199dcd5cb662d9a" ON "model_performance" ("period_start") `);
        await queryRunner.query(`CREATE INDEX "IDX_f63e803dd6c18ef4d894fa22ef" ON "model_performance" ("model_version", "period_start") `);
        await queryRunner.query(`CREATE TABLE "alerts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "ticker" character varying NOT NULL, "companyName" character varying NOT NULL, "alertType" character varying NOT NULL, "condition" jsonb NOT NULL, "triggered" boolean NOT NULL DEFAULT false, "triggeredAt" TIMESTAMP, "triggerPrice" numeric(15,2), "isActive" boolean NOT NULL DEFAULT true, "isRecurring" boolean NOT NULL DEFAULT false, "notificationChannels" jsonb NOT NULL DEFAULT '{"email":true,"push":false,"sms":false}', "expiresAt" TIMESTAMP, "message" character varying, "triggerCount" integer NOT NULL DEFAULT '0', "lastCheckedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_60f895662df096bfcdfab7f4b96" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f2678f7b11e5128abbbc451190" ON "alerts" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_3c21c0d164404f1debd6b2c83e" ON "alerts" ("ticker") `);
        await queryRunner.query(`CREATE INDEX "IDX_a0b01c35a79c907e1301d88153" ON "alerts" ("triggeredAt") `);
        await queryRunner.query(`CREATE TABLE "watchlists" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "name" character varying NOT NULL, "description" character varying, "tickers" jsonb NOT NULL DEFAULT '[]', "isDefault" boolean NOT NULL DEFAULT false, "isPublic" boolean NOT NULL DEFAULT true, "sortOrder" integer NOT NULL DEFAULT '0', "color" character varying, "icon" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_aa3c717b50a10f7a435c65eda5a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4ee2b11c974ca3f516a391e154" ON "watchlists" ("userId") `);
        await queryRunner.query(`CREATE TABLE "positions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "portfolioId" uuid NOT NULL, "ticker" character varying NOT NULL, "companyName" character varying NOT NULL, "quantity" numeric(15,6) NOT NULL, "averageCost" numeric(15,2) NOT NULL, "currentPrice" numeric(15,2) NOT NULL, "totalCost" numeric(15,2) NOT NULL, "currentValue" numeric(15,2) NOT NULL, "unrealizedPL" numeric(15,2) NOT NULL, "unrealizedPLPercent" numeric(10,2) NOT NULL, "dayChangePercent" numeric(10,2) NOT NULL DEFAULT '0', "dayChangeDollar" numeric(15,2) NOT NULL DEFAULT '0', "allocationPercent" numeric(10,2) NOT NULL DEFAULT '0', "sector" character varying, "industry" character varying, "assetType" character varying, "status" character varying NOT NULL DEFAULT 'open', "transactions" jsonb, "openedAt" TIMESTAMP, "closedAt" TIMESTAMP, "realizedPL" numeric(15,2), "realizedPLPercent" numeric(10,2), "notes" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_17e4e62ccd5749b289ae3fae6f3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0d5f4889958502cbba1feb0f82" ON "positions" ("portfolioId") `);
        await queryRunner.query(`CREATE INDEX "IDX_209a30cb60ce3b09a6987a86fd" ON "positions" ("ticker") `);
        await queryRunner.query(`CREATE INDEX "IDX_156deeb21544f00f2704cd6b72" ON "positions" ("openedAt") `);
        await queryRunner.query(`CREATE TABLE "portfolios" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "name" character varying NOT NULL, "description" character varying, "cashBalance" numeric(15,2) NOT NULL DEFAULT '0', "totalValue" numeric(15,2) NOT NULL DEFAULT '0', "totalCost" numeric(15,2) NOT NULL DEFAULT '0', "totalReturnPercent" numeric(10,2) NOT NULL DEFAULT '0', "totalReturnDollar" numeric(15,2) NOT NULL DEFAULT '0', "dayChangePercent" numeric(10,2) NOT NULL DEFAULT '0', "dayChangeDollar" numeric(15,2) NOT NULL DEFAULT '0', "currency" character varying NOT NULL DEFAULT 'USD', "isActive" boolean NOT NULL DEFAULT true, "isDefault" boolean NOT NULL DEFAULT false, "allocation" jsonb, "sectorAllocation" jsonb, "performanceHistory" jsonb, "riskMetrics" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_488aa6e9b219d1d9087126871ae" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e4e66691a2634fcf5525e33ecf" ON "portfolios" ("userId") `);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying NOT NULL, "password" character varying NOT NULL, "firstName" character varying NOT NULL, "lastName" character varying NOT NULL, "phoneNumber" character varying, "role" character varying NOT NULL DEFAULT 'user', "emailVerified" boolean NOT NULL DEFAULT false, "emailVerificationToken" character varying, "passwordResetToken" character varying, "passwordResetExpires" TIMESTAMP, "profilePicture" character varying, "subscriptionPlan" character varying NOT NULL DEFAULT 'free', "subscriptionExpires" TIMESTAMP, "isActive" boolean NOT NULL DEFAULT true, "lastLoginAt" TIMESTAMP, "preferences" jsonb, "googleId" character varying, "githubId" character varying, "oauthData" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE TABLE "fundamental_data" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "ticker" character varying(20) NOT NULL, "date" date NOT NULL, "peRatio" numeric(10,2), "pbRatio" numeric(10,2), "psRatio" numeric(10,2), "pegRatio" numeric(10,2), "evToEbitda" numeric(10,2), "roe" numeric(10,4), "roa" numeric(10,4), "profitMargin" numeric(10,4), "operatingMargin" numeric(10,4), "grossMargin" numeric(10,4), "debtToEquity" numeric(10,2), "currentRatio" numeric(10,2), "quickRatio" numeric(10,2), "interestCoverage" numeric(10,2), "revenueGrowth" numeric(10,4), "earningsGrowth" numeric(10,4), "epsGrowth" numeric(10,4), "eps" numeric(10,2), "bookValue" numeric(10,2), "dividendYield" numeric(10,2), "marketCap" bigint, "revenue" bigint, "netIncome" bigint, "totalDebt" bigint, "totalEquity" bigint, "totalAssets" bigint, "operatingCashFlow" bigint, "freeCashFlow" bigint, "sector" character varying(50), "industry" character varying(100), "dataSource" character varying(50) NOT NULL DEFAULT 'yahoo', "dataQuality" numeric(5,2) NOT NULL DEFAULT '100', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e19ddc130f911f183cb8427ca0c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1042568fa1fe5050bedf241aa6" ON "fundamental_data" ("ticker") `);
        await queryRunner.query(`CREATE INDEX "IDX_cc58cc3d6bda3532bd1a68cd02" ON "fundamental_data" ("date") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_1926f1b1b16e509b291f4a0cda" ON "fundamental_data" ("ticker", "date") `);
        await queryRunner.query(`CREATE TABLE "sentiment_data" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "ticker" character varying(20) NOT NULL, "date" date NOT NULL, "newsSentiment" numeric(5,2) NOT NULL DEFAULT '50', "newsArticleCount" integer NOT NULL DEFAULT '0', "newsSentimentChange" numeric(5,2), "socialSentiment" numeric(5,2) NOT NULL DEFAULT '50', "socialMentionCount" integer NOT NULL DEFAULT '0', "socialSentimentChange" numeric(5,2), "redditSentiment" numeric(5,2) NOT NULL DEFAULT '50', "redditMentions" integer NOT NULL DEFAULT '0', "twitterSentiment" numeric(5,2) NOT NULL DEFAULT '50', "twitterMentions" integer NOT NULL DEFAULT '0', "analystBuyRatings" integer NOT NULL DEFAULT '0', "analystHoldRatings" integer NOT NULL DEFAULT '0', "analystSellRatings" integer NOT NULL DEFAULT '0', "analystConsensus" numeric(5,2) NOT NULL DEFAULT '50', "analystTargetPrice" numeric(10,2), "insiderBuyCount" integer NOT NULL DEFAULT '0', "insiderSellCount" integer NOT NULL DEFAULT '0', "insiderBuyValue" bigint NOT NULL DEFAULT '0', "insiderSellValue" bigint NOT NULL DEFAULT '0', "compositeSentiment" numeric(5,2) NOT NULL DEFAULT '50', "sentimentVolatility" numeric(5,2) NOT NULL DEFAULT '0', "sentimentTrend" character varying(20) NOT NULL DEFAULT 'neutral', "topKeywords" jsonb, "sentimentBreakdown" jsonb, "dataSource" character varying(100) NOT NULL DEFAULT 'multi-source', "dataQuality" numeric(5,2) NOT NULL DEFAULT '100', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b4a89349412d867c27149768a97" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_461269c5608e7ed8382d11515f" ON "sentiment_data" ("ticker") `);
        await queryRunner.query(`CREATE INDEX "IDX_09283782ee4a285e4a8776f017" ON "sentiment_data" ("date") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_4472d0e61d7fbd065fffdd8aa4" ON "sentiment_data" ("ticker", "date") `);
        await queryRunner.query(`CREATE TABLE "market_context" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "date" date NOT NULL, "nifty50Price" numeric(12,2), "nifty50Change" numeric(10,4), "sensexPrice" numeric(12,2), "sensexChange" numeric(10,4), "bankNiftyPrice" numeric(12,2), "bankNiftyChange" numeric(10,4), "indiaVix" numeric(10,2), "volatilityRegime" character varying(20) NOT NULL DEFAULT 'medium', "sp500Price" numeric(12,2), "sp500Change" numeric(10,4), "vixPrice" numeric(10,2), "usdInrRate" numeric(10,4), "goldPrice" numeric(12,2), "crudeOilPrice" numeric(12,2), "nifty50AdvancingStocks" integer, "nifty50DecliningStocks" integer, "advanceDeclineRatio" numeric(5,2), "nifty50Above200DMA" numeric(5,2), "nseVolume" bigint, "bseVolume" bigint, "fiiNetBuying" numeric(10,2), "diiNetBuying" numeric(10,2), "inflationRate" numeric(5,2), "repoRate" numeric(5,2), "gdpGrowthRate" numeric(5,2), "bond10YearYield" numeric(10,2), "marketRegime" character varying(20) NOT NULL DEFAULT 'neutral', "trendRegime" character varying(20) NOT NULL DEFAULT 'sideways', "marketSentiment" numeric(5,2) NOT NULL DEFAULT '50', "dataSource" character varying(100) NOT NULL DEFAULT 'multi-source', "dataQuality" numeric(5,2) NOT NULL DEFAULT '100', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_46539568da1845d2da86aa676e5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_0d2d547bac55a304515dac2dc6" ON "market_context" ("date") `);
        await queryRunner.query(`CREATE TABLE "paper_accounts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "start_capital" numeric(14,2) NOT NULL, "cash" numeric(14,2) NOT NULL, "target_amount" numeric(14,2), "target_days" integer, "challenge_started_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_d6da1a592c629f5da5cb4c6e1a6" UNIQUE ("name"), CONSTRAINT "PK_660b7540c8d0b342144c5653d6d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "paper_trades" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "account_id" uuid NOT NULL, "ticker" character varying(20) NOT NULL, "name" character varying(255), "side" character varying(4) NOT NULL, "qty" integer NOT NULL, "price" numeric(14,4) NOT NULL, "fees" numeric(14,4) NOT NULL, "executed_at" TIMESTAMP WITH TIME ZONE NOT NULL, "status" character varying(10) NOT NULL, "stop_loss" numeric(14,4), "target" numeric(14,4), "exit_price" numeric(14,4), "exit_at" TIMESTAMP WITH TIME ZONE, "realized_pnl" numeric(14,4), "note" text, "entry_context" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5a569a3797709ab0d6128583705" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ff4b51f7f36129f30f0f822773" ON "paper_trades" ("ticker", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_e6d081b5ba6d827c391aba0d0d" ON "paper_trades" ("account_id", "status") `);
        await queryRunner.query(`CREATE TABLE "ensemble_weights" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "ticker" character varying(20) NOT NULL, "horizon_days" integer NOT NULL, "weights" jsonb, "updated_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_b6671248b10378ef10bf3428db2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5c92ee3d41789630a5193121d7" ON "ensemble_weights" ("ticker") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_6a3a4fe0697526544d024c5be0" ON "ensemble_weights" ("ticker", "horizon_days") `);
        await queryRunner.query(`CREATE TABLE "rank_snapshots" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "date" date NOT NULL, "ticker" character varying(20) NOT NULL, "composite" double precision NOT NULL, "components" jsonb, "percentile" double precision NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4a278e3d0104f764107ff5a68cc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_cf262f28c1ad65e11b55663b92" ON "rank_snapshots" ("date", "ticker") `);
        await queryRunner.query(`CREATE INDEX "IDX_315ba0062c30cfc611084c28b5" ON "rank_snapshots" ("date") `);
        await queryRunner.query(`CREATE TABLE "kelly_drift" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "date" date NOT NULL, "closed_trades" integer NOT NULL, "measured_p" double precision, "measured_b" double precision, "half_kelly_pct" double precision, "applied" character varying(40) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_aebe04f84fe97fcd6f484c1940d" UNIQUE ("date"), CONSTRAINT "PK_6f0cd22e5cde7d7f9a2140cadc6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "intelligence_sources" DROP CONSTRAINT "UQ_intelligence_sources_hash"`);
        // Reconciliation (schema-diff vs live 2026-09-06): the live DB's intelligence
        // PK constraints carry TypeORM entity-derived hash names (created by the old
        // synchronize:true), while 1788217200000-CreateIntelligenceEngine used custom
        // names. Rename so a migrations-built DB is byte-identical to live and future
        // migration:generate runs stay clean. Verified: columns/indexes/other
        // constraints matched exactly; these 5 names were the only difference.
        await queryRunner.query(`ALTER TABLE "intelligence_sources" RENAME CONSTRAINT "PK_intelligence_sources" TO "PK_4b959cb5037e73560a4741e78b5"`);
        await queryRunner.query(`ALTER TABLE "financial_facts" RENAME CONSTRAINT "PK_financial_facts" TO "PK_90a20fa44d66b91e49755669746"`);
        await queryRunner.query(`ALTER TABLE "intelligence_metrics" RENAME CONSTRAINT "PK_intelligence_metrics" TO "PK_af67534d15ec1fcb092aebeb8a9"`);
        await queryRunner.query(`ALTER TABLE "intelligence_evidence" RENAME CONSTRAINT "PK_intelligence_evidence" TO "PK_4390d1e4f54f82f98fa4865eb7a"`);
        await queryRunner.query(`ALTER TABLE "macro_observations" RENAME CONSTRAINT "PK_macro_observations" TO "PK_51a5c273c25f7ca269a74f8ab7d"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_3ceffb6c5978bc8c876fa9231e" ON "intelligence_sources" ("content_hash") `);
        await queryRunner.query(`CREATE INDEX "IDX_3082ffe2565e19f04a334802c5" ON "intelligence_sources" ("ticker", "provider", "published_at") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_8ef19d320d9e0f560d313a617d" ON "financial_facts" ("source_id", "raw_concept", "context_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ca6266bd2686dece6ceb9c3994" ON "financial_facts" ("ticker", "concept", "period_end", "consolidation") `);
        await queryRunner.query(`CREATE INDEX "IDX_60ad7e80fc516677fbeff6fbff" ON "intelligence_metrics" ("ticker", "metric", "period", "methodology") `);
        await queryRunner.query(`CREATE INDEX "IDX_291a1c4400f535d3fcaa5577e9" ON "intelligence_evidence" ("ticker", "category", "as_of_date") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_527c1ea055fe94ff80ecc2ec84" ON "macro_observations" ("indicator", "period", "source_url") `);
        await queryRunner.query(`ALTER TABLE "analysis" ADD CONSTRAINT "FK_b2d38b93507cfa35220bece9776" FOREIGN KEY ("stock_id") REFERENCES "stocks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_history" ADD CONSTRAINT "FK_5b1ccf76084011cd76f72d59cf4" FOREIGN KEY ("stock_id") REFERENCES "stocks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_metrics" ADD CONSTRAINT "FK_377b3a813f758908be9b0fb1369" FOREIGN KEY ("stock_id") REFERENCES "stocks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "alerts" ADD CONSTRAINT "FK_f2678f7b11e5128abbbc4511906" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "watchlists" ADD CONSTRAINT "FK_4ee2b11c974ca3f516a391e1543" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "positions" ADD CONSTRAINT "FK_0d5f4889958502cbba1feb0f822" FOREIGN KEY ("portfolioId") REFERENCES "portfolios"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "portfolios" ADD CONSTRAINT "FK_e4e66691a2634fcf5525e33ecf5" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "paper_trades" ADD CONSTRAINT "FK_e37a98247bc7ca59e754d7a9c77" FOREIGN KEY ("account_id") REFERENCES "paper_accounts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "paper_trades" DROP CONSTRAINT "FK_e37a98247bc7ca59e754d7a9c77"`);
        await queryRunner.query(`ALTER TABLE "portfolios" DROP CONSTRAINT "FK_e4e66691a2634fcf5525e33ecf5"`);
        await queryRunner.query(`ALTER TABLE "positions" DROP CONSTRAINT "FK_0d5f4889958502cbba1feb0f822"`);
        await queryRunner.query(`ALTER TABLE "watchlists" DROP CONSTRAINT "FK_4ee2b11c974ca3f516a391e1543"`);
        await queryRunner.query(`ALTER TABLE "alerts" DROP CONSTRAINT "FK_f2678f7b11e5128abbbc4511906"`);
        await queryRunner.query(`ALTER TABLE "stock_metrics" DROP CONSTRAINT "FK_377b3a813f758908be9b0fb1369"`);
        await queryRunner.query(`ALTER TABLE "stock_history" DROP CONSTRAINT "FK_5b1ccf76084011cd76f72d59cf4"`);
        await queryRunner.query(`ALTER TABLE "analysis" DROP CONSTRAINT "FK_b2d38b93507cfa35220bece9776"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_527c1ea055fe94ff80ecc2ec84"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_291a1c4400f535d3fcaa5577e9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_60ad7e80fc516677fbeff6fbff"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ca6266bd2686dece6ceb9c3994"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8ef19d320d9e0f560d313a617d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3082ffe2565e19f04a334802c5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3ceffb6c5978bc8c876fa9231e"`);
        await queryRunner.query(`ALTER TABLE "macro_observations" RENAME CONSTRAINT "PK_51a5c273c25f7ca269a74f8ab7d" TO "PK_macro_observations"`);
        await queryRunner.query(`ALTER TABLE "intelligence_evidence" RENAME CONSTRAINT "PK_4390d1e4f54f82f98fa4865eb7a" TO "PK_intelligence_evidence"`);
        await queryRunner.query(`ALTER TABLE "intelligence_metrics" RENAME CONSTRAINT "PK_af67534d15ec1fcb092aebeb8a9" TO "PK_intelligence_metrics"`);
        await queryRunner.query(`ALTER TABLE "financial_facts" RENAME CONSTRAINT "PK_90a20fa44d66b91e49755669746" TO "PK_financial_facts"`);
        await queryRunner.query(`ALTER TABLE "intelligence_sources" RENAME CONSTRAINT "PK_4b959cb5037e73560a4741e78b5" TO "PK_intelligence_sources"`);
        await queryRunner.query(`ALTER TABLE "intelligence_sources" ADD CONSTRAINT "UQ_intelligence_sources_hash" UNIQUE ("content_hash")`);
        await queryRunner.query(`DROP TABLE "kelly_drift"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_315ba0062c30cfc611084c28b5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cf262f28c1ad65e11b55663b92"`);
        await queryRunner.query(`DROP TABLE "rank_snapshots"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6a3a4fe0697526544d024c5be0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5c92ee3d41789630a5193121d7"`);
        await queryRunner.query(`DROP TABLE "ensemble_weights"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e6d081b5ba6d827c391aba0d0d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ff4b51f7f36129f30f0f822773"`);
        await queryRunner.query(`DROP TABLE "paper_trades"`);
        await queryRunner.query(`DROP TABLE "paper_accounts"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0d2d547bac55a304515dac2dc6"`);
        await queryRunner.query(`DROP TABLE "market_context"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4472d0e61d7fbd065fffdd8aa4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_09283782ee4a285e4a8776f017"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_461269c5608e7ed8382d11515f"`);
        await queryRunner.query(`DROP TABLE "sentiment_data"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1926f1b1b16e509b291f4a0cda"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cc58cc3d6bda3532bd1a68cd02"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1042568fa1fe5050bedf241aa6"`);
        await queryRunner.query(`DROP TABLE "fundamental_data"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e4e66691a2634fcf5525e33ecf"`);
        await queryRunner.query(`DROP TABLE "portfolios"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_156deeb21544f00f2704cd6b72"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_209a30cb60ce3b09a6987a86fd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0d5f4889958502cbba1feb0f82"`);
        await queryRunner.query(`DROP TABLE "positions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4ee2b11c974ca3f516a391e154"`);
        await queryRunner.query(`DROP TABLE "watchlists"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a0b01c35a79c907e1301d88153"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3c21c0d164404f1debd6b2c83e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f2678f7b11e5128abbbc451190"`);
        await queryRunner.query(`DROP TABLE "alerts"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f63e803dd6c18ef4d894fa22ef"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_caa57b9555c199dcd5cb662d9a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6cac3a44e37dfe68bdea52faa6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5ce1a82d1bdcd1a3327079f5b2"`);
        await queryRunner.query(`DROP TABLE "model_performance"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8afbc587e50337b08dcd8d6ef9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7cca4cae8ab0866704bd243180"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e7899294dc3846d07ecf04a45e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_956e0bab09fd4308d65b5d11e8"`);
        await queryRunner.query(`DROP TABLE "prediction_logs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a29d3b86c5655964fc148df010"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2a30d1386addd706a59abfaff1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f55830c6120cba8b1a55c69121"`);
        await queryRunner.query(`DROP TABLE "model_registry"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_263fd13ae5081852e6ca4a817e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1bcaeebd54521d9e08b069e0e8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d0de7d8eefb2a0711ca74a4665"`);
        await queryRunner.query(`DROP TABLE "training_samples"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dd9b32c339b5ba46c1a84c3aa0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_312d2d22eb16ebdcf477c6504c"`);
        await queryRunner.query(`DROP TABLE "cron_execution_logs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ed3365b823c13b0828fa5f29ca"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a47b99659613a5464a6bcd2d3d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0ec5d60fe5e30c1484ae6a98aa"`);
        await queryRunner.query(`DROP TABLE "rate_limit_logs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_67e5527b870ca7e013858ed3d7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_90ea57d41bf1ba91c6981e4ade"`);
        await queryRunner.query(`DROP TABLE "stocks"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6e589ac2bbe419ca83f43cce8a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1e2797169280396ab49bb91f4b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4458bfad30b2757b22cd9376ec"`);
        await queryRunner.query(`DROP TABLE "stock_metrics"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4c6083eda45a5e0e12e706424f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f4735409aecba218d2a47a7594"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cc252ec5ff13eb9dd089a464d2"`);
        await queryRunner.query(`DROP TABLE "stock_history"`);
        await queryRunner.query(`DROP TABLE "analysis"`);
        await queryRunner.query(`DROP TYPE "public"."analysis_risk_level_enum"`);
        await queryRunner.query(`DROP TYPE "public"."analysis_recommendation_enum"`);
        await queryRunner.query(`ALTER TABLE "macro_observations" ADD CONSTRAINT "UQ_macro_observation" UNIQUE ("indicator", "period", "source_url")`);
        await queryRunner.query(`ALTER TABLE "financial_facts" ADD CONSTRAINT "UQ_financial_fact_source_concept_context" UNIQUE ("raw_concept", "context_id", "source_id")`);
        await queryRunner.query(`CREATE INDEX "IDX_intelligence_evidence_lookup" ON "intelligence_evidence" ("ticker", "category", "as_of_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_intelligence_metrics_lookup" ON "intelligence_metrics" ("ticker", "metric", "period", "methodology") `);
        await queryRunner.query(`CREATE INDEX "IDX_financial_facts_lookup" ON "financial_facts" ("ticker", "concept", "period_end", "consolidation") `);
        await queryRunner.query(`CREATE INDEX "IDX_intelligence_sources_ticker_provider_date" ON "intelligence_sources" ("ticker", "provider", "published_at") `);
        await queryRunner.query(`ALTER TABLE "intelligence_evidence" ADD CONSTRAINT "FK_intelligence_evidence_source" FOREIGN KEY ("source_id") REFERENCES "intelligence_sources"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "financial_facts" ADD CONSTRAINT "FK_financial_fact_source" FOREIGN KEY ("source_id") REFERENCES "intelligence_sources"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
    }

}
